CMD_INIT = "init"
CMD_SHUTDOWN = "shutdown"
CMD_START = "start"
CMD_STOP = "stop"
CMD_STATUS = "status"

VALID_RECORD_FORMATS = {"mp4", "raw"}
DEFAULT_STREAM_IP = "127.0.0.1"
DEFAULT_STREAM_IP_PORT = 5600
DEFAULT_CAMERA_DEVICE = "/dev/video0"
DEFAULT_RECORD_FORMAT = "mp4"
DEFAULT_HTTP_HOST = "0.0.0.0"
DEFAULT_HTTP_PORT = 8001
DEFAULT_WIDTH = 640
DEFAULT_HEIGHT = 512
DEFAULT_FPS = 30
DEFAULT_TARGET_FOLDER = "./output"
